### PR TITLE
Create dunhill.json

### PR DESCRIPTION
**Pull request by dunhill-high**
add dunhill

### CODE REVIEW

**Comment by jessysaurusrex** [comment]
Hi @dunhill-high! Confirming receipt of your RPC endpoint, but the chain_id here doesn't match the one your team signed up with-- is this newer one the one that you would like to use for the competition? Once your team whitelists the IP addresses from the confirmation email, you are all set for Game of Zones. 🚀

**Comment by dunhill-high** [comment]
Thanks @jessysaurusrex
please update this "dunhillchain" chainid for the competition.
Thanks

**Comment by jessysaurusrex** [comment]
Just updated your chain_id! You're all set to go!

**Comment by dunhill-high** [comment]
Thanks @jessysaurusrex

**Pull request merged**
