### PR TITLE
Phase 1 GOZ

### PR DESCRIPTION
**Pull request by raendem**

### CODE REVIEW

**Comment by jessysaurusrex** [comment]
Hi @raendem! What team name did you register with? We unfortunately can't find a record of this chain_id being submitted during registration.

**Comment by raendem** [comment]
Hi, can I participate without registering? Probably running different chains for different purposes.  I was too late in signing up. I presume without registration I can still run the chains and participate, just that I won't be getting the score/rewards.

**Comment by jessysaurusrex** [comment]
I think we can likely accomodate this -- drop me an email at gameofzones at cosmosnetwork . dev with your Cosmos address for the testnet, and you're good to go.

**Comment by raendem** [comment]
I probably am spreading my resources too thin. I'm also participating in other blockchains' testnet/challenges.

Thank you for accommodating the late registration. Really appreciate it. I don't have a use case at this point, I think I'll be watching on the sideline. 

Excited to see the outcome of GoZ!

**Comment by jessysaurusrex** [comment]
Best of luck during adversarial testnet season!!

**Pull request closed without merging**
