### PR TITLE
Fix contestant info json files

### PR DESCRIPTION
**Pull request by rk-p2p**

### CODE REVIEW

**Comment by rk-p2p** [comment]
@zmanian Hello! Can you check my pr and merge it?

**Comment by jackzampolin** [comment]
Can you please turn your whitespace deletion off on your editor? This PR 129 files and makes a large number of changes. Can you please fix that?

**Comment by rk-p2p** [comment]
@jackzampolin I resolved conflicts and remove prettify json, trailing whitespaces, etc.

**Comment by rk-p2p** [comment]
@jackzampolin @zmanian ping?

**Pull request closed without merging**
